# -*- coding: utf-8 -*-
"""Alfido_task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XoYxH9BOBht73h-7PchyhjV0IEBXLwug
"""

df = pd.read_csv("/content/tested.csv")
df.head(10)

df.shape

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df.describe()

df['Survived'].value_counts()

sns.countplot(x=df['Survived'], hue=df['Pclass'])

sns.countplot(x=df['Sex'], hue=df['Survived'])

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder ()
df['Sex']= labelencoder. fit_transform(df['Sex'])
df. head()

df['Sex']

df['Survived']

sns.countplot(x=df["Sex"],hue=df["Survived"])

df.isna().sum()

df_final=df
df_final.head(10)

X=df[['Pclass','Sex']]
Y=df['Survived']

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state =0)

from sklearn.linear_model import LogisticRegression
log = LogisticRegression (random_state = 0)
log.fit (X_train, Y_train)

pred= print(log.predict (X_test))

print(Y_test)

import warnings
warnings.filterwarnings("ignore")
res=log.predict([[6,0]])
if(res==0):
  print("Sorry!!! They are Not Survived")
else:
  print("They are Survived")